### PR TITLE
Emissive Property Fix (Revised)

### PR DESCRIPTION
**Pull request by wdavies973**
Fixes an issue https://github.com/libgdx/libgdx/issues/5529

### CODE REVIEW

**Comment by mgsx-dev** [comment]
@wdavies973 sorry again, could your remove your formatting changes (spaces, end of line, etc). The idea is to keep only necessary changes.

FYI, you don't need to close and open a new PR, all you have to do is to push on the same branch again, the PR will be automatically updated by GitHub ;-)
This is why it's recommended to work on a dedicated branch for each PR.

**Comment by tommyettinger** [comment]
@mgsx-dev It's been 2.5 months and the PR is still in limbo. Do we even have anyone involved in this repo who can accept a PR, regardless of its formatting? It's been like 3 years since the last commit...

**Comment by wdavies973** [comment]
@tommyettinger yeah, basically these guys kept nit picking my formatting for like 3 lines of code so I got tired of continually changing it when it literally looked just fine in visual studio. I'm hosting the fixed version here if you'd like: https://github.com/wdavies973/fbx-conv. I've also compiled the fixed .exe in the releases category.

**Comment by mgsx-dev** [comment]
@tommyettinger yeah, i know but i can't do more here :man_shrugging: we need a maintainer here.

I don't know if @xoppa still involved, maybe @Tom-Ski could help us out?

**Comment by mgsx-dev** [comment]
@wdavies973 i think you have an issue with git/visual studio because it doesn't look good in git diff... anyway i don't think it wasn't merged because of this, maintainers could cleanup formatting during merge. You did a good job.

**Pull request closed without merging**
