### PR TITLE
Output G3DJ With Optimisations

### PR DESCRIPTION
**Pull request by Ranjit-S**
- New command option -s
- Outputs JSON without any whitespace
- and removes unnecessary trailing zeros after decimal point

### CODE REVIEW

**Comment by xoppa** [comment]
What's the use-case for this?

**Comment by Ranjit-S** [comment]
On mobile it saves us time downloading and parsing g3dj files.

**Comment by xoppa** [comment]
Well that's why there's g3db

**Comment by Ranjit-S** [comment]
We are moving towards the binary format soon, just thought this would be a nice addition.

Anyway, its your call.

**Comment by xoppa** [comment]
I'd rather not complicate the code without having at least one valid use-case for it.

**Pull request closed without merging**
